### ISSUE TITLE
Violation of rule when code is formatted (Prettier)

### ISSUE THREAD

**Issue by zextis** [linthtml/linthtml#147]
Hello! 👋 The following formatted code should **not** be a violation of the "attribute values cannot be empty" rule, but is currently being interpreted as such. 

![image](https://user-images.githubusercontent.com/19380973/74052576-2d34f480-49a8-11ea-9779-1d2623297864.png)

**Comment by KamiKillertO** [comment]
Indeed :thinking:, thanks for reporting. Can you share your config to help me reproduce ?

**Comment by KamiKillertO** [comment]
@zextis :point_up: having your config will help me a lot :pray:

**Comment by zextis** [comment]
@KamiKillertO sorry for the late reply, and I have no config. Its just when Prettier formats my HTML code and puts them on separate lines (like in the pic), lint-html thinks the attributes aren't there.

**Comment by KamiKillertO** [comment]
Ok so it means that the default config is generating this error :thinking:. Thanks for the reply

**Comment by KamiKillertO** [comment]
I'm not able to reproduce this error.
Are you still having the error ?
Can you copy/paste the complete error message ?

**Comment by KamiKillertO** [comment]
@zextis ?
