### ISSUE TITLE
Error linthtml: Cannot find global or local @linthtml/linthtml package

### ISSUE THREAD

**Issue by pacocom** [linthtml/linthtml#151]
Error:
linthtml: Cannot find global or local @linthtml/linthtml package

![image](https://user-images.githubusercontent.com/7735329/75234355-c2165b00-57ba-11ea-9f10-2e69626917b9.png)

![image](https://user-images.githubusercontent.com/7735329/75234387-d3f7fe00-57ba-11ea-928f-801a0333bb9b.png)

Version: 1.42.1 (user setup)
Commit: c47d83b293181d9be64f27ff093689e8e7aed054
Date: 2020-02-11T14:45:59.656Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.17763
![image](https://user-images.githubusercontent.com/7735329/75234402-db1f0c00-57ba-11ea-97dd-edfe13ec801f.png)

**Comment by pacocom** [comment]
Sorry I close the issue only need:

`npm install @linthtml/linthtml --save-dev`
`npx linthtml --init`

to create `.linthtmlrc` file

**Comment by hansnolte** [comment]
> 
> 
> Sorry I close the issue. I needed to create `.linthtmlrc` file:
> 
> `npm install @linthtml/linthtml --save-dev`
> `npx linthtml --init`
> 
> then `.linthtmlrc` file was created successfully.

Hello pacocom,

can you please tell me where you copied the .linthtmlrc?
(The path to the .linthtmlrc.)

And how did you create them without suffix.
(Simply renamed?)
I can only choose between JavaScript, YAML and JSON.

Thanks in advance

**Comment by cherif87** [comment]
Hello, Why do I see this error message in visual studio code, please advise : 

Error linthtml: Cannot find global or local @linthtml/linthtml

**Comment by KamiKillertO** [comment]
@cherif87 you have this error message because the vscode-linthtml extension cannot find a local or global installation for LintHTML. Make sure you have LintHTML locally or globally ([how to](https://github.com/linthtml/linthtml#installation-and-usage)).
If you still have the message after installation please open an issue [here](https://github.com/linthtml/vscode-linthtml)
