### ISSUE TITLE
Error with Angular

### ISSUE THREAD

**Issue by pacocom** [linthtml/linthtml#152]
In my case I have Angular 8 (Angular 9 too):
![image](https://user-images.githubusercontent.com/7735329/75236842-b036b700-57be-11ea-9875-73dbec9ff541.png)
![image](https://user-images.githubusercontent.com/7735329/75237691-13751900-57c0-11ea-8149-e49eefd2efc6.png)

It's possible to add custom attr, tag, etc... for compatibility with Angular?

Thanks.

**Comment by KamiKillertO** [comment]
At the moment there's no support for angular or any other framework. I'll have support for Angular and other frameworks but not soon (after v0.7 or more). There's other things that need to be fixed/improved before.

In the meantime you can solve your problem by changing the config for the rule `attr-name-style`, the rule accept a Regexp as config. Based on your screenshots, if you use the following config you will remove all the lint errors

```javascript
// .linthtmlrc.js
const DASH = "[a-z\d]+(-[a-z\d]+)*";

// With the new config format
module.exports = {
  "rules": {
    "attr-name-style": [
      "error",
      new RegExp(`^${DASH}$|\\[${DASH}\\]|\\*ng[A-Z]\\w+`)
    ]
  }
}

// If you use the legacy config format
module.exports = {
  "attr-name-style":  new RegExp(`^${DASH}$|\\[${DASH}\\]|\\*ng[A-Z]\\w+`)
}
```

**Comment by pacocom** [comment]
Thank.

Do I need to change .linthtmlrc file (in documentation you can use .linthtmlrc file) to .linthtmlrc.js file only or any more configuration?

Thank.

**Comment by KamiKillertO** [comment]
Yes, you can use the `.linthtmlrc` file instead.

**Comment by KamiKillertO** [comment]
@pacocom are still having issues ?

**Comment by pacocom** [comment]
Thank!! I close it.
