### ISSUE TITLE
[rule] Finding broken links

### ISSUE THREAD

**Issue by pixelastic** [linthtml/linthtml#155]
Is there a rule to allow finding broken links?

For example if I have a `<a href="foo.html">foo</a>` but I don't have a `foo.html` page?

**Comment by KamiKillertO** [comment]
At the moment no, and I'm not planning on adding this kind of rule at the moment.
Maybe It could a good candidate for a plugin (plugins are planned for v0.6.0)

**Comment by pixelastic** [comment]
Thanks for the comment. In the meantime I found https://urlint.co/ that does this specifically.

**Comment by KamiKillertO** [comment]
👍 this is a nice tool 👍
