### ISSUE TITLE
Don't support browser？

### ISSUE THREAD

**Issue by Ryuurock** [linthtml/linthtml#162]
Don't support browser？

**Comment by KamiKillertO** [comment]
:thinking: I did not try to use it in the browser but I think it should work.

**Comment by KamiKillertO** [comment]
```javascript

**Comment by Ryuurock** [comment]
> This should work
> 
> ```js
> import * as linthtml from "@linthtml/linthtml";
> let rulesConfig = {
>   rules: {...}
> };
> linthtml('<div>foo</div>', rulesConfig);
> ```

Thanks!
