### ISSUE TITLE
Search .linthtmlrc up to home directory (not just cwd).

### ISSUE THREAD

**Issue by ndixon** [linthtml/linthtml#164]
Currently, `stopDir` is set to `process.cwd()`, which isn't ideal for projects with configuration files located in home directories. Provide a cli option that reverts the `stopDir` setting to the default cosmiconfig behavior.

Perhaps something like `--config-stop-dir` that accepts `cwd` (default) or `home`.

**Comment by KamiKillertO** [comment]
It seems that it's how Eslint [behave](https://eslint.org/docs/user-guide/configuring#using-configuration-files-1) so I don't mind  reporting this behavior.

I've planned to improve the config file management in `0.5.0` with the search of a config file for each linted files from the current directory to `process.cwd`. So stopping at the `HOME` instead is not a big deal 👍

**Comment by KamiKillertO** [comment]
Hello @ndixon I've just published a new beta version (0.5.0-beta.3) which improve how file config are managed. Now for each file linted LintHTML will search for a config file from the file local folder to the `HOME` directory

**Comment by KamiKillertO** [comment]
I've release LintHTML 0.5.0 with this feature
