### ISSUE TITLE
"class-style": "bem" does not accept any dash in class name.

### ISSUE THREAD

**Issue by akumanara** [linthtml/linthtml#195]
As you can see in the naming conventions (Naming rules) for BEM below, it says the following:
Words are separated by a hyphen (-).

So for example, the class class="hp-intro__logo" is valid, but the linter throws the following error.
Value "" of attribute "class" does not respect the format: bem

Resource:
https://en.bem.info/methodology/naming-convention/#naming-rules

**Comment by KamiKillertO** [comment]
@akumanara I cannot reproduce your issue 😞 . Can you provide the following information to help me?

- Your version od linthtml
- you config file
- the HTML causing the issue

**Comment by akumanara** [comment]
@KamiKillertO Thanks for your response, i just saw that it didnt like an extra space! my bad! 
Cheers

**Comment by KamiKillertO** [comment]
Happy to here that there's no issue with the bem analyzer 😊 . But there is still an issue here, the linter should not report an issue for  spaces ><

**Comment by akumanara** [comment]
> Happy to here that there's no issue with the bem analyzer 😊 . But there is still an issue here, the linter should not report an issue for spaces ><

Fun times!
in that case you can see the error in the following section (it has 2 spaces after hp-intro)
<section class="hp-intro  section-space">
