### ISSUE TITLE
`linthtml --init` not working for JSON format

### ISSUE THREAD

**Issue by acalvo** [linthtml/linthtml#244]
`npx linthtml --init` and selecting `JSON` as a format (either with the legacy or the new config) generates a `.linthtml.json` file with this content:

```
[object Object]
```

**Comment by KamiKillertO** [comment]
🤦 Indeed

**Comment by KamiKillertO** [comment]
Thanks for reporting, I've just published a new release with a fix for this issue, #243 and #245

**Comment by acalvo** [comment]
Thank you for the super fast fix!! 😄
