### ISSUE TITLE
Unexpected issue with globbing through subfolder trees

### ISSUE THREAD

**Issue by jaredcwhite** [linthtml/linthtml#256]
I seem to be having an odd issue where the `**` glob pattern is only going one level deep and not searching recursively. To find all the files I'm looking for I have to repeat `**` several times, like so:

```
yarn linthtml src/**/*.{html,erb,serb,liquid,md} src/**/**/*.{html,erb,serb,liquid,md} src/**/**/**/*.{html,erb,serb,liquid,md}
```

**Comment by KamiKillertO** [comment]
Ok, first question, what version of LintHTML are you using?
Have you try adding quotes around the glob pattern? `Likes yarn linthtml "src/**/*.{html,erb,serb,liquid,md}"`

**Comment by jaredcwhite** [comment]
@KamiKillertO The quotes trick worked! All set now :+1:
