### ISSUE TITLE
Rule "line-max-len-ignore-regex" exist?

### ISSUE THREAD

**Issue by nikolai-shabalin** [linthtml/linthtml#281]
[line-max-len-ignore-regex documentation](https://github.com/linthtml/linthtml/tree/develop/lib/rules/line-max-len#line-max-len-ignore-regex)

I trying to disable the rule, but it doesn't seem to exist.

```js
module.exports = {  
  rules: {
   "line-max-len-ignore-regex" : false,
   }
 }
 ```
 
 Console alert
 
 ```bash
 Rule "line-max-len-ignore-regex" does not exist.
 ```

**Comment by KamiKillertO** [comment]
Yes, this is not considered as a rule with the new config format. Move this line outside `rules` and you will no longer have the error. I think it's explained in the migration guide 🤔

**Comment by nikolai-shabalin** [comment]
Thank you
