### ISSUE TITLE
How to allow closing multiline tags with no content?

### ISSUE THREAD

**Issue by Bestulo** [linthtml/linthtml#305]
![image](https://user-images.githubusercontent.com/23301025/108770176-61863f00-7530-11eb-81ad-d3f01bf6264c.png)

![image](https://user-images.githubusercontent.com/23301025/108770191-664af300-7530-11eb-8a70-38a5867502b5.png)

This is generated by Prettier and I don't disagree with it. But I don't know which rule, if any, I can modify on `.linthtmlrc.js` to allow me to close tags this way.

**Comment by KamiKillertO** [comment]
🤔 this should not report an error indeed

**Comment by KamiKillertO** [comment]
@Bestulo I've just released the version 0.6.3 which contains a fix for your problem. Tell me if it's ok now

**Comment by Bestulo** [comment]
I think it is. I haven't had that issue anymore.
