### ISSUE TITLE
REGEXP config items do not support REGEXPs as strings "ignore.test is not a function"

### ISSUE THREAD

**Issue by tylercrocker** [linthtml/linthtml#374]
If you use the JSON config and have something like ```"id-class-ignore-regex": "/{{.*}}/"``` the config pulls it in and tries to run "test" directly on the string rather than trying to convert it from a string first to a REGEXP.

I was able to switch this to the JS config format and it works but I have to use `raw-ignore-regex` instead of the former.

**Comment by KamiKillertO** [comment]
True, true I should convert the config to a regexp before 👍 . Thanks for reporting

**Comment by KamiKillertO** [comment]
@tylercrocker I've released LintHTML v0.8 which contains a fix for this issue
