### ISSUE TITLE
Which config is used when installed globally and on project?

### ISSUE THREAD

**Issue by viT-1** [linthtml/linthtml#422]
Your package behaves the same as eslint?
Which one is used when I linting by cli and which one is used by VSCode plugin? They are same?

**Comment by KamiKillertO** [comment]
LintHTML behave almost the same as eslint yes. When linting files it will first search for the nearest config file for each HTML file and then lint the file

The vscode extension works the same as the eslint's one sine version 0.3.0.

When opening an HTML file the extension will : 
1. locate the LintHTML bin (it can be a local deps, global one or an absolute path form config)
2. Search for the nearest LintTHML config file
3. Lint the file
