### ISSUE TITLE
Problem with package.json configuration, extends custom json file rules

### ISSUE THREAD

**Issue by viT-1** [linthtml/linthtml#436]
Linthtml v0.8.4 runned as npm srcipt `"linth": "linthtml src/**/*.html"`
All ok if I use `.linthtmlrc.js` file with content:
```js
const baseExtends = [
	'@linthtml/linthtml-config-recommended',
	'./linthtml.rules.json',
];

const conf = {
	extends: baseExtends,
}

module.exports = conf;
```

But if I move `extends` to `package.json` file, [all my redefined rule settings](https://github.com/viT-1/systemjs-babel-es6-vue/blob/aff43139cbfcaa92a403e41a1111d3777860ef43/linthtml.rules.json) in `./linthtml.rules.json` don't apply.

package.json:
```json
"linthtml": {
	"extends": [
		"@linthtml/linthtml-config-recommended",
		"./linthtml.rules.json"
	]
},
"stylelint": {
	"extends": [
		"stylelint-config-standard",
		"stylelint-config-idiomatic-order",
		"./stylelint.rules.json"
	],
	"ignoreFiles": [
		"./dist/**/*"
	]
}
```

linthtml.rules.json:
```json
{
	"rules": {
		"attr-name-style": false,
		"attr-quote-style": false,
		"attr-req-value": false,
		"doctype-first": false,
		"indent-style": false,
		"indent-width": false,
		"title-max-len": false
	}
}
```

**Comment by KamiKillertO** [comment]
🤔thanks for reporting, I'll look into.

**Comment by viT-1** [comment]
@KamiKillertO  Sorry, my mistake, acted by analogy with Stylelint.
