### ISSUE TITLE
[Question] linthtml/core ships unmaintained version of core-js 

### ISSUE THREAD

**Issue by alecslupu** [linthtml/linthtml#584]
Currently, when adding to package.json the package `@linthtml/linthtml` any version, we get in the upgrade notes a deprecation warning which complains that "core-js@2.6.12: core-js@<3.23.3 is no longer maintained..."

```
npm WARN deprecated core-js@2.6.12: core-js@<3.23.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Some versions have web compatibility issues. Please, upgrade your dependencies to the actual version of core-js.
```

Inspecting my package-lock.json file, i have noticed the following dependency tree:

- "core-js" < 3.23 is a dependency of "babel-runtime"
- "babel-runtime" is a dependency of "rewiremock"
- "rewiremock" is a dependency of "@linthtml/core"

When i got to this repository, i have noticed that you are referencing "rewiremock" in only 3 files: 

- [packages/core/package.json](https://github.com/linthtml/linthtml/blob/f2546c5069fb7935669a680c70fe6a610c8f15bc/packages/core/package.json#L64)
- [packages/core/src/__tests__/linter.test.ts](https://github.com/linthtml/linthtml/blob/f2546c5069fb7935669a680c70fe6a610c8f15bc/packages/core/src/__tests__/linter.test.ts#L4)
- [packages/core/src/__tests__/config_reader/index.test.ts](https://github.com/linthtml/linthtml/blob/f2546c5069fb7935669a680c70fe6a610c8f15bc/packages/core/src/__tests__/config_reader/index.test.ts#L193)

Inspecting further, i noticed that i do not have anywhere the `rewiremock` referenced in my `node_modules/@linthtml` code base, except for package-json. 

Form this investigation, I get to ask the following questions: 
- is there any plan on actually replacing the library with a newer alternative that does not list unmaintained version of core-js as dependency ?
- since you are not shipping the tests, is there any alternate place in the project where you could install the library ?

**Comment by KamiKillertO** [comment]
It was a mistake, `rewiremock` is only used in tests and should have never been a dev dependency.
Thanks for reporting, I have released a new version that no longer ships it

**Comment by andreslucena** [comment]
> I have released a new version that no longer ships it

Awesome @KamiKillertO, thanks for the responsiveness and quickness on fixing this issue!

**Comment by alecslupu** [comment]
@KamiKillertO thank you ! I am closing this as no longer relevant :)
