### ISSUE TITLE
[cli] Always returning 0 response-code

### ISSUE THREAD

**Issue by acalvo** [linthtml/linthtml#61]
I was about to include LintHTML in our CI pipeline and found that even with errors the pipeline continued executing as if the linting had gone OK.

This happens because the CLI seems to always exit with a 0 value. Other linters exit with non-zero whenever a linting error occurred.

To test this, provoke a HTML linting error, run LintHTML, and then execute `echo $?`.

**Comment by KamiKillertO** [comment]
Thanks for reporting 👍, I'm happy to have some reports regarding real uses of LintHTML.
