### ISSUE TITLE
[rule] raw-ignore-regex

### ISSUE THREAD

**Issue by acalvo** [linthtml/linthtml#64]
In one of our projects we use [Hugo](https://gohugo.io/) which has this kind of HTML markup: https://github.com/gohugoio/gohugoioTheme/blob/master/layouts/partials/site-nav.html#L15

Note this attribute:  `class="dim link{{ if $currentPage.IsMenuCurrent "global" . }} gray {{else}} light-silver{{ end }}"`

It can have unescaped double quotes (`"`) inside the attribute value, which naturally confuses the linter as it thinks the attribute finishes in there. To solve this, I use the `raw-ignore-regex` rule of htmllint, which allows me to drop everything starting with `{{` and ending with `}}` before doing any parsing. This caused other problems, though. Suppose this code:

```html
<p>
  {{ .aVariable }}
</p>
```

This would cause problems as the text would be removed, leaving just the indentation and provoking a linting error. So what I did was make the regex in `raw-ingnore-regex` also match (remove) the spaces before and after `{{ }}`. And had to enable `indent-width-cont` as a related consequence, I think.

It seems that `raw-ignore-text` isn't available anymore in LintHTML, is it? Can you think of any elegant way to deal with this problem? :/

**Comment by KamiKillertO** [comment]
`raw-ignore-text` still exist but it's not a rule. It's something that is used internally to ignore part of the dom. It's not documented because I still don't really know how it works.

**Comment by KamiKillertO** [comment]
Ok I've had a quick look to the code and I've have a quick fix that should solve your problem. Instead of removing the text that match the regex , I'll replace it with dummy content. 

That way code like this one won't report any errors

```html<p>
  {{ .aVariable }}
</p>
```

**Comment by acalvo** [comment]
> Instead of removing the text that match the regex , I'll replace it with dummy content.

Sounds good!! 😄

Are you thinking of a constant dummy text? Because I just realized that if it was random text I could also turn on some other rules. For example `id-no-dup`, which generates an error if there is something like `id="{{ .var1 }}"` in an element and `id="{{ .var2 }}"` somewhere else.

**Comment by KamiKillertO** [comment]
More a constant dummy char (`¤`) that will be used to replace every char matching the regex.
For example 

```html
<p>
  {{ .aVariable }}
</p>
```

Will be transformed in 

```html
<p>
  ¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤
</p>
```

I've updated rules like `id-no-dup`, `class-no-dup`... to ignore everything that contain only `¤`. It's a temporary solution until I find a better solution.

**Comment by KamiKillertO** [comment]
@acalvo I've released a new version with this "fix" + the one for #61

**Comment by acalvo** [comment]
Thanks! I just checked that #61 is working great now 🎉. Will play around to see if I find any other issue/suggestion 😊.

**Comment by acalvo** [comment]
@KamiKillertO Tried LintHTML v0.2.6 and is working great both in our Angular and Hugo projects 🎉. I also tried it in a third project (much more simple, didn't expect to have any problems with it) and worked like a charm. Thank you for the bug fixes! ❤️

Would it be possible to release a new version of [vscode-linthtml](https://github.com/linthtml/vscode-linthtml) that uses LintHTML 0.2.6? It'd be the last thing I'd need to make the MRs changing htmllint to LintHTML in these three projects 😄

**Comment by KamiKillertO** [comment]
Done 👍

**Comment by acalvo** [comment]
Thank you! I just migrated successfully the three projects I'm involved in to LintHTML 😄.

Will make a documentation PR soon enough ☺️.
